###
A simple example service that returns some data.
###
angular.module("synthesizer")

.factory "AudioVisualizerService",(AudioAnalyserService,$window) ->
  canvas = $window.document.querySelector('.oscilloscope')
  analyser = AudioAnalyserService.getanalyser()
  canvasCtx = canvas.getContext('2d')
  drawFrame = () ->
    WIDTH=$window.getClientWidth()
    HEIGHT=200
    drawVisual = requestAnimationFrame(draw)
    analyser.getByteTimeDomainData dataArray
    canvasCtx.fillStyle = 'rgb(200, 200, 200)'
    canvasCtx.fillRect 0, 0, WIDTH, HEIGHT
    canvasCtx.lineWidth = 2
    canvasCtx.strokeStyle = 'rgb(0, 0, 0)'
    canvasCtx.beginPath()
    sliceWidth = WIDTH * 1.0 / bufferLength
    x = 0
    i = 0
    while i < bufferLength
      v = dataArray[i] / 128.0
      y = v * HEIGHT / 2
      if i == 0
        canvasCtx.moveTo x, y
      else
        canvasCtx.lineTo x, y
      x += sliceWidth
      i++
    canvasCtx.lineTo canvas.width, canvas.height / 2
    canvasCtx.stroke()
    draw()

    # ---
    # generated by js2coffee 2.0.4
